[package]
name = "rake"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0"
jack = "0.13.3"
rack = { git = "https://github.com/lzj15/rack.git" }
ringbuf = "0.4.8"
uuid = { version = "1.19.0", features = ["v4"] }
